apiVersion: v1
kind: Service
metadata:
  namespace: provisioner
  name: order-meow-provisioner
  labels:
    app: provisioner
spec:
  type: ClusterIP
  ports:
    - name: provisioner
      port: 8080
  selector:
    app: provisioner
